[project]
name = "transcript-summariser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic_ai",
    "youtube_transcript_api",
    "PyPDF2",
    "bs4",
    "requests"
]
